import assert from "node:assert/strict"
import {test} from "node:test"
import React from "react"
import {createRequire} from "node:module"
import {JSDOM} from "jsdom"
import type {WebsiteContentV2} from "../lib/types/website"
const initial:WebsiteContentV2={
    schema_version: 2,
    identity: { company_name: "Demo Co", trade_code: "plumbing", custom_trade_label: null, headline: "Careful local work", description: "", about: "", established_year: null },
    public_contact: { phone: "(555) 555-1212", email: "hello@example.com", social_links: [], address_visibility: "hidden", display_address: null },
    branding: { template_id: "modern", template_version: 2, theme: { palette: "slate", font_pair_id: "system", logo_size: "medium", density: "comfortable", button_style: "rounded" }, logo_asset_id: null, hero_asset_id: null, hero_focal_point: null, logo_alt: "", hero_alt: "", legacy_logo_url: null, legacy_hero_image_url: null },
    availability: null, services: [], service_areas: [], legacy_service_area: "", projects: [], credentials: [], testimonials: [], faqs: [], sections: [{ key: "hero", order: 0, enabled: true, background: "default" }, { key: "contact", order: 1, enabled: true, background: "default" }], seo: { title: null, description: null, share_image_asset_id: null },
  }
initial.testimonials=[{id:"t1",order:0,text:"Fictional words for design testing.",display_name:"Sample homeowner",date:null,rating:null,source_label:null,source_permalink:null}]
initial.faqs=[{id:"f1",order:0,question:"What details help?",answer:"Photos are optional."}]
const saved={slug:"fictional",content:initial,contractor_uuid:"fixture",booking_slug:null,draft_revision:8,published_revision:3,is_published:false,has_unpublished_changes:true,published_at:null,updated_at:null,profile_timezone:"America/Los_Angeles"}
test("actual settings freezes delayed restore, blocks saves and clears undo",async()=>{
 const dom=new JSDOM("<!doctype html><html><body></body></html>",{url:"http://localhost"});Object.assign(globalThis,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,DocumentFragment:dom.window.DocumentFragment,localStorage:dom.window.localStorage});Object.defineProperty(globalThis,"navigator",{value:dom.window.navigator,configurable:true});globalThis.requestAnimationFrame=fn=>{fn(0);return 0};dom.window.confirm=()=>true;localStorage.setItem("website-setup-step:fictional","5");
 const req=createRequire(import.meta.url);req.extensions[".css"]=()=>({});const {render,fireEvent,act,cleanup}=req("@testing-library/react");const {NextIntlClientProvider}=req("next-intl");const {api}=req("../lib/api");const {WebsiteSettings}=req("../components/websites/website-settings");const {websiteHistoryApi}=req("../lib/website-history-api");const originalHistory={...websiteHistoryApi};const original={getWebsite:api.getWebsite,restoreWebsiteRevision:api.restoreWebsiteRevision,saveWebsite:api.saveWebsite};let finish:((value:unknown)=>void)|undefined;let saveCalls=0;let restoreCalls=0;api.getWebsite=async()=>saved;websiteHistoryApi.getWebsiteRevisionPage=async()=>({items:[{revision:7,schema_version:2,reason:"save",created_at:"2026-10-02T12:00:00Z"}],next_before:null});websiteHistoryApi.getWebsiteRevisionSnapshot=async()=>({revision:7,content:initial});api.restoreWebsiteRevision=async()=>{restoreCalls++;return new Promise(resolve=>{finish=resolve})};api.saveWebsite=async(payload:any)=>{saveCalls++;return {...saved,content:payload.content,draft_revision:9}};
 try{let view:any;await act(async()=>{view=render(React.createElement(NextIntlClientProvider,{locale:"en",messages:req("../messages/en.json")},React.createElement(WebsiteSettings)))});await act(async()=>{fireEvent.click(view.getByRole("button",{name:new RegExp(req("../messages/en.json").website.setup.steps.business)}))});await act(async()=>{fireEvent.change(view.container.querySelector("#website-headline"),{target:{value:"Before restore local edit"}})});assert.equal(view.getByRole("button",{name:req("../messages/en.json").website.setup.undo}).disabled,false);await act(async()=>{await new Promise(resolve=>setTimeout(resolve,1400))});assert.equal(saveCalls,1);await act(async()=>{fireEvent.click(view.getByRole("button",{name:new RegExp(req("../messages/en.json").website.setup.steps.review)}))});await act(async()=>{fireEvent.click(view.getByRole("button",{name:"Preview & restore"}))});await act(async()=>{fireEvent.click(view.getByRole("button",{name:"Restore as draft"}))});assert.equal(restoreCalls,1);assert.ok(view.container.querySelector("[inert]"));await act(async()=>{await new Promise(resolve=>setTimeout(resolve,1400))});assert.equal(saveCalls,1);await act(async()=>{finish!({...saved,draft_revision:10,content:{...initial,identity:{...initial.identity,headline:"Restored words"}}})});assert.equal(view.container.querySelector("[inert]"),null);assert.equal(view.getByRole("button",{name:req("../messages/en.json").website.setup.undo}).disabled,true);assert.equal(view.getByRole("button",{name:req("../messages/en.json").website.setup.redo}).disabled,true);assert.equal(saveCalls,1);assert.equal(view.queryByRole("button",{name:"Restore as draft"}),null);
 }finally{cleanup();Object.assign(api,original);Object.assign(websiteHistoryApi,originalHistory);dom.window.close()}
})
