import {test} from 'node:test'
import assert from 'node:assert/strict'
import {validateEstimate,validateEstimateFiles} from '../lib/estimate-request'
const valid={name:'Alex Sample',email:'alex@example.test',phone:'5551234567',address:'123 Fictional Street',project_type:'painting',description:'Paint the kitchen.'}
test('estimate requires all six fields and keeps project enums',()=>{assert.deepEqual(validateEstimate(valid),{});assert.equal(Object.keys(validateEstimate({name:'',email:'',phone:'',address:'',project_type:'',description:''})).length,6);assert.ok(validateEstimate({...valid,project_type:'free_text'}).project_type)})
test('estimate rejects oversize and invalid photos without altering input',()=>{const photos=[new File(['x'],'project.jpg',{type:'image/jpeg'})];assert.equal(validateEstimateFiles(photos),'');assert.ok(validateEstimateFiles(Array(6).fill(photos[0])));assert.ok(validateEstimateFiles([new File(['x'],'bad.svg',{type:'image/svg+xml'})]));assert.equal(photos.length,1)})
import {estimateRetryDisposition} from '../lib/estimate-retry'
test('explicit machine codes decide retry without detail-string heuristics',()=>{assert.equal(estimateRetryDisposition(409,'in_flight'),'same-request');assert.equal(estimateRetryDisposition(409,'payload_mismatch'),'mismatch');assert.equal(estimateRetryDisposition(503,'retryable_failure'),'same-request');assert.equal(estimateRetryDisposition(429,'rate_limit'),'editable');assert.equal(estimateRetryDisposition(503,'not_ready'),'editable');assert.equal(estimateRetryDisposition(422,'invalid_fields'),'editable');assert.equal(estimateRetryDisposition(422,'challenge_failed'),'editable')})
import {submitWebsiteEstimate,estimateCapabilities,EstimateRequestError} from '../lib/estimate-request'
test('unavailable capability does not claim ready',async()=>{const original=global.fetch;global.fetch=async()=>new Response('{}',{status:503});try{assert.equal((await estimateCapabilities('fixture')).enabled,false)}finally{global.fetch=original}})
test('submit accepts only confirmed acceptance and preserves request identity across retry',async()=>{const original=global.fetch;const calls:FormData[]=[];global.fetch=async(_url,init)=>{calls.push(init?.body as FormData);if(calls.length===1)return new Response(JSON.stringify({detail:{code:'in_flight',message:'processing'}}),{status:409});return new Response(JSON.stringify({accepted:true,request_key:'stable-key'}),{status:201})};try{await assert.rejects(submitWebsiteEstimate('fixture',valid,[],{items:[]},'stable-key','','token'),error=>error instanceof EstimateRequestError&&error.code==='in_flight');await submitWebsiteEstimate('fixture',valid,[],{items:[]},'stable-key','','token');assert.equal(calls[0].get('request_key'),calls[1].get('request_key'));assert.equal(calls[0].get('description'),calls[1].get('description'))}finally{global.fetch=original}})
test('ambiguous response is never treated as success',async()=>{const original=global.fetch;global.fetch=async()=>new Response('{}',{status:201});try{await assert.rejects(submitWebsiteEstimate('fixture',valid,[],{items:[]},'stable-key','','token'),EstimateRequestError)}finally{global.fetch=original}})

test('uncertain prior delivery preserves identity through later security/readiness failure',()=>{for(const code of ['challenge_unavailable','challenge_failed','challenge_required','not_ready','rate_limit'])assert.equal(estimateRetryDisposition(503,code,true),'same-request');assert.equal(estimateRetryDisposition(422,'invalid_fields',true),'editable')})
