"use client"

import { useMemo, useState } from "react"

export interface PreviewEntry {
  model: string
  src: string
}

export function PreviewTabs({
  entries,
  prompt,
  host,
}: {
  entries: PreviewEntry[]
  prompt: string
  host: string
}) {
  const [activeModel, setActiveModel] = useState(entries[0]?.model ?? "")
  const [promptOpen, setPromptOpen] = useState(false)

  const active = useMemo(
    () => entries.find((e) => e.model === activeModel) ?? entries[0],
    [activeModel, entries],
  )

  return (
    <div style={styles.page}>
      <header style={styles.header}>
        <div>
          <div style={styles.eyebrow}>Engineering · dev preview</div>
          <h1 style={styles.title}>Estimate model comparison</h1>
          <div style={styles.subtle}>
            {entries.length} model{entries.length === 1 ? "" : "s"} · host{" "}
            <code style={styles.code}>{host || "unknown"}</code> · not visible in production
          </div>
        </div>
        <a href="/dev/preview/prompt.md" target="_blank" rel="noopener noreferrer" style={styles.linkBtn}>
          Raw prompt ↗
        </a>
      </header>

      <div style={styles.tabBar}>
        {entries.map((entry) => {
          const isActive = entry.model === active?.model
          return (
            <button
              key={entry.model}
              type="button"
              onClick={() => setActiveModel(entry.model)}
              style={{
                ...styles.tab,
                ...(isActive ? styles.tabActive : null),
              }}
            >
              {entry.model}
            </button>
          )
        })}
      </div>

      <details
        open={promptOpen}
        onToggle={(e) => setPromptOpen((e.target as HTMLDetailsElement).open)}
        style={styles.promptCard}
      >
        <summary style={styles.promptSummary}>
          <span style={styles.promptSummaryTitle}>Prompt sent to the model</span>
          <span style={styles.promptSummaryHint}>
            {promptOpen ? "Hide" : "Show"} · {prompt.length.toLocaleString()} chars
          </span>
        </summary>
        <pre style={styles.promptBody}>{prompt || "(prompt file not found)"}</pre>
      </details>

      <div style={styles.iframeWrap}>
        {active ? (
          <iframe
            key={active.model}
            src={active.src}
            title={`Estimate · ${active.model}`}
            style={styles.iframe}
          />
        ) : null}
      </div>

      <footer style={styles.footer}>
        Generated by <code style={styles.code}>ContractorBackend/dev/render_estimate_html.py</code>.
        Re-run that script and copy the new HTMLs into{" "}
        <code style={styles.code}>contrac-slayer/public/dev/preview/</code> to refresh.
      </footer>
    </div>
  )
}

const styles: Record<string, React.CSSProperties> = {
  page: {
    minHeight: "100vh",
    background: "#fafafa",
    padding: "24px 16px 40px",
    fontFamily:
      "ui-sans-serif, -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif",
    color: "#0f172a",
  },
  header: {
    maxWidth: 1280,
    margin: "0 auto 16px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 16,
    flexWrap: "wrap",
  },
  eyebrow: {
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    color: "#64748b",
    marginBottom: 4,
  },
  title: {
    fontSize: 22,
    fontWeight: 700,
    margin: 0,
    letterSpacing: "-0.01em",
  },
  subtle: { color: "#64748b", fontSize: 13, marginTop: 6 },
  code: {
    fontFamily:
      "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, monospace",
    fontSize: 12,
    background: "#f1f5f9",
    padding: "2px 6px",
    borderRadius: 4,
  },
  linkBtn: {
    fontSize: 13,
    fontWeight: 500,
    textDecoration: "none",
    color: "#0f172a",
    background: "#fff",
    border: "1px solid #e5e7eb",
    padding: "8px 12px",
    borderRadius: 10,
  },
  tabBar: {
    maxWidth: 1280,
    margin: "0 auto 12px",
    display: "flex",
    gap: 6,
    flexWrap: "wrap",
    padding: 4,
    background: "#fff",
    border: "1px solid #e5e7eb",
    borderRadius: 14,
  },
  tab: {
    fontFamily: "inherit",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    padding: "8px 14px",
    borderRadius: 10,
    border: "1px solid transparent",
    background: "transparent",
    color: "#0f172a",
    transition: "background .15s, border-color .15s",
  },
  tabActive: {
    background: "#0f172a",
    color: "#fff",
    borderColor: "#0f172a",
  },
  promptCard: {
    maxWidth: 1280,
    margin: "0 auto 12px",
    background: "#fff",
    border: "1px solid #e5e7eb",
    borderRadius: 14,
    overflow: "hidden",
  },
  promptSummary: {
    cursor: "pointer",
    padding: "12px 16px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    listStyle: "none",
  },
  promptSummaryTitle: { fontSize: 14, fontWeight: 600 },
  promptSummaryHint: { fontSize: 12, color: "#64748b" },
  promptBody: {
    margin: 0,
    padding: "12px 16px 16px",
    borderTop: "1px solid #e5e7eb",
    background: "#f8fafc",
    fontFamily:
      "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, monospace",
    fontSize: 12,
    lineHeight: 1.55,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    maxHeight: 320,
    overflow: "auto",
  },
  iframeWrap: {
    maxWidth: 1280,
    margin: "0 auto",
    background: "#fff",
    border: "1px solid #e5e7eb",
    borderRadius: 14,
    overflow: "hidden",
    height: "calc(100vh - 280px)",
    minHeight: 520,
  },
  iframe: {
    width: "100%",
    height: "100%",
    border: 0,
    display: "block",
    background: "#fafafa",
  },
  footer: {
    maxWidth: 1280,
    margin: "16px auto 0",
    color: "#94a3b8",
    fontSize: 12,
    textAlign: "center",
  },
}
