"use client"
import { useEffect, useRef, useState } from "react"
import { useLocale, useTranslations } from "next-intl"
import {websiteHistoryApi as api} from "@/lib/website-history-api"
import { isWebsiteV2, type WebsiteContent, type WebsiteState } from "@/lib/types/website"
import { useWebsiteDraftPreviews } from "@/lib/use-website-draft-previews"
import { ContractorWebsite } from "./contractor-website"
import { Button } from "@/components/ui/button"
type Revision={revision:number;schema_version:number;created_at:string;reason:string}
export function WebsiteRevisionHistory({saved,onRestore,blocked}:{saved:WebsiteState;onRestore:(revision:number)=>Promise<void>;blocked:boolean}) {
 const locale=useLocale();const t=useTranslations("website.phase4");const [items,setItems]=useState<Revision[]>([]);const [next,setNext]=useState<number|null>(null);const [expanded,setExpanded]=useState(false);const [listLoading,setListLoading]=useState(false);const [previewLoading,setPreviewLoading]=useState(false);const [reload,setReload]=useState(0);const loading=listLoading||previewLoading;const [error,setError]=useState("");const [selected,setSelected]=useState<{revision:number;content:WebsiteContent}|null>(null);const [restoring,setRestoring]=useState(false);const generation=useRef(0);const previewGeneration=useRef(0);const loadingRef=useRef(false)
 const {previews,failed}=useWebsiteDraftPreviews(selected&&isWebsiteV2(selected.content)?selected.content:null,!!selected)
 useEffect(()=>{let active=true;const current=++generation.current;setSelected(null);setItems([]);setNext(null);setPreviewLoading(false);setExpanded(false);setError("");setListLoading(true);loadingRef.current=true;void api.getWebsiteRevisionPage().then(page=>{if(active){setItems(page.items);setNext(page.next_before)}}).catch(()=>{if(active)setError(t("historyError"))}).finally(()=>{if(active){setListLoading(false);loadingRef.current=false}});return()=>{active=false;if(generation.current===current)generation.current=current+1}},[saved.slug,saved.draft_revision,reload,t])
 async function more(){if(next===null||loadingRef.current)return;loadingRef.current=true;setListLoading(true);setError("");const current=generation.current;try{const page=await api.getWebsiteRevisionPage(next);if(current===generation.current){setItems(old=>[...old,...page.items.filter(i=>!old.some(o=>o.revision===i.revision))]);setNext(page.next_before)}}catch{if(current===generation.current)setError(t("historyError"))}finally{if(current===generation.current){setListLoading(false);loadingRef.current=false}}}
 async function preview(revision:number){const current=++previewGeneration.current;const listGeneration=generation.current;setPreviewLoading(true);setError("");try{const snapshot=await api.getWebsiteRevisionSnapshot(revision);if(current===previewGeneration.current&&listGeneration===generation.current)setSelected(snapshot)}catch{if(current===previewGeneration.current&&listGeneration===generation.current)setError(t("historyError"))}finally{if(current===previewGeneration.current&&listGeneration===generation.current)setPreviewLoading(false)}}
 async function restore(){if(!selected||blocked||restoring)return;setRestoring(true);try{await onRestore(selected.revision);setSelected(null)}catch{setError(t("historyError"))}finally{setRestoring(false)}}
 return <section className="space-y-3"><h3 className="font-semibold">{t("history")}</h3><p className="text-xs text-slate-500">{t("retention")}</p>{error&&<div><p role="alert" className="text-sm text-red-700">{error}</p><Button type="button" onClick={()=>setReload(n=>n+1)} disabled={loading||restoring}>{t("retry")}</Button></div>}{items.slice(0,expanded?undefined:5).map(item=><div key={item.revision} className="flex items-center justify-between gap-3 rounded border p-3 text-xs"><span>{t("revision",{revision:item.revision})}<span className="block text-slate-500">{new Date(item.created_at).toLocaleString(locale)} · {item.reason==="publish"?t("publishedSnapshot"):item.reason.startsWith("restore:")?t("restoredSnapshot"):t("savedSnapshot")}</span>{item.revision===saved.published_revision&&<span>{t("published")}</span>}</span>{item.revision!==saved.draft_revision?<Button type="button" size="sm" variant="ghost" disabled={loading||restoring} onClick={()=>void preview(item.revision)}>{t("previewRestore")}</Button>:<span>{t("current")}</span>}</div>)}{items.length>5&&!expanded&&<Button type="button" variant="ghost" onClick={()=>setExpanded(true)}>{t("viewAll")}</Button>}{expanded&&next!==null&&<Button type="button" disabled={loading} variant="outline" onClick={()=>void more()}>{t("loadMore")}</Button>}{loading&&<p role="status" className="text-sm">{t("loading")}</p>}{selected&&<div className="space-y-4 rounded border p-4"><h4 className="font-semibold">{t("revision",{revision:selected.revision})}</h4><p className="text-sm">{t("restoreHelp")}</p>{failed&&<p role="alert" className="text-sm">{t("previewAssetError")}</p>}<ContractorWebsite site={{...saved,content:selected.content}} preview assetPreviews={previews}/><div className="flex gap-3"><Button type="button" variant="outline" onClick={()=>{previewGeneration.current++;setSelected(null);setPreviewLoading(false)}} disabled={restoring}>{t("cancel")}</Button><Button type="button" onClick={()=>void restore()} disabled={blocked||restoring||loading}>{t("restore")}</Button></div>{blocked&&<p className="text-sm">{t("saveBeforeRestore")}</p>}</div>}</section>
}
