"use client"
import {useEffect,useRef,useState} from "react"
import {EstimateChallenge} from "./estimate-challenge"
import {MeasurementsInput} from "@/components/measurements-input"
import {MapboxAddressInput} from "@/components/mapbox-address-input"
import {useEstimateRequest} from "./use-estimate-request"
import {estimateCapabilities,PROJECT_TYPES,type EstimateFields} from "@/lib/estimate-request"
import styles from "@/components/websites/website.module.css"
const labels:Record<keyof EstimateFields,string>={name:"Full name",email:"Email",phone:"Phone",address:"Project address",project_type:"Project type",description:"Project description"}
export function WebsiteEstimateForm({slug,company,preview=false,legacyUrl,phone,email}:{slug:string;company:string;preview?:boolean;legacyUrl:string;phone?:string|null;email?:string|null}) {
 const f=useEstimateRequest({websiteSlug:slug});const [ready,setReady]=useState<boolean|null>(null);const [siteKey,setSiteKey]=useState<string>("");const result=useRef<HTMLDivElement>(null)
 useEffect(()=>{if(preview)return;const controller=new AbortController();estimateCapabilities(slug,controller.signal).then(value=>{setReady(value.enabled&&Boolean(process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY)&&(!value.site_key||value.site_key===process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY));setSiteKey(process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY||"")}).catch(()=>{if(!controller.signal.aborted)setReady(false)});return()=>controller.abort()},[slug,preview])
 useEffect(()=>{if(f.isSubmitted)result.current?.focus()},[f.isSubmitted])
 if(f.isSubmitted)return <div tabIndex={-1} ref={result} role="status" className={styles.estimateSuccess}><p className={styles.eyebrow}>Request received</p><h2>Thank you for the details.</h2><p>{company} can review your project and contact you about next steps.</p><a className={styles.primary} href={`/sites/${encodeURIComponent(slug)}`}>Back to website</a></div>
 const input=(key:"name"|"email"|"phone",type:string,autoComplete:string)=><label className={styles.estimateField} htmlFor={`estimate-${key}`}><span>{labels[key]} <span aria-hidden="true">*</span></span><input id={`estimate-${key}`} name={key} type={type} autoComplete={autoComplete} value={f.formData[key]} required maxLength={key==="phone"?20:255} aria-invalid={Boolean(f.fieldErrors[key])} aria-describedby={f.fieldErrors[key]?`estimate-error-${key}`:undefined} onChange={e=>f.setFormData({...f.formData,[key]:e.target.value})}/>{f.fieldErrors[key]&&<span id={`estimate-error-${key}`} className={styles.estimateFieldError}>{f.fieldErrors[key]}</span>}</label>
 return <form className={styles.estimateForm} noValidate onSubmit={e=>{if(preview||ready!==true){e.preventDefault();return}void f.handleSubmit(e)}}>
  <p className={styles.estimateNote}>All fields marked * are required. Photos and measurements are optional.</p>
  {preview&&<p role="status" className={styles.estimateNotice}>Demo only. Requests cannot be sent from the website editor.</p>}
  {!preview&&ready!==true&&<p role="status" className={styles.estimateNotice}>{ready===null?"Checking request availability...":"Online requests are not available yet. You can use the standalone request form below."}</p>}
  {!preview&&ready===false&&<div className={styles.estimateNotice}><a href={legacyUrl} className={styles.primary}>Open request form</a>{phone&&<p><a href={`tel:${phone.replace(/[^+\d]/g,"")}`}>{phone}</a></p>}{email&&<p><a href={`mailto:${email}`}>{email}</a></p>}</div>}
    {f.error&&<div role="alert" className={styles.estimateError}><p>{f.error}</p>{Object.entries(f.fieldErrors).map(([key,message])=><a key={key} href={`#estimate-${key}`} onClick={e=>{e.preventDefault();document.getElementById(`estimate-${key}`)?.focus()}}>{message}</a>)}</div>}
  {f.locked&&!f.isSubmitted&&!f.isSubmitting&&<p className={styles.estimateNotice}>Your original details are held for a safe retry. Retry checks or sends that same request. If it is still processing, wait a few seconds before retrying. Do not start another request while delivery is uncertain.</p>}
  <fieldset disabled={f.isSubmitting||f.locked||preview} className={styles.estimateFields}>
   <legend>Contact details</legend><div className={styles.estimateRow}>{input("name","text","name")}{input("email","email","email")}</div>{input("phone","tel","tel")}
   <div className={styles.estimateField}><MapboxAddressInput id="estimate-address" label="Project address" required fallbackToPlain errorId="estimate-error-address" defaultValue={f.formData.address} error={f.fieldErrors.address} inputClassName={styles.estimateAddress} onInputChange={value=>{f.setAddressData(null);f.setFormData(prev=>({...prev,address:value}))}} onAddressSelect={value=>{f.setAddressData(value);if(value)f.setFormData(prev=>({...prev,address:value.formatted_address||""}))}}/>{f.fieldErrors.address&&<span id="estimate-error-address" className={styles.estimateFieldError}>{f.fieldErrors.address}</span>}</div>
   <label className={styles.estimateField} htmlFor="estimate-project_type">Project type *<select id="estimate-project_type" required value={f.formData.project_type} aria-invalid={Boolean(f.fieldErrors.project_type)} aria-describedby={f.fieldErrors.project_type?"estimate-error-project_type":undefined} onChange={e=>f.setFormData({...f.formData,project_type:e.target.value})}><option value="">Select project type</option>{PROJECT_TYPES.map(type=><option key={type} value={type}>{type.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}</option>)}</select>{f.fieldErrors.project_type&&<span id="estimate-error-project_type" className={styles.estimateFieldError}>{f.fieldErrors.project_type}</span>}</label>
   <label className={styles.estimateField} htmlFor="estimate-description">Project description *<textarea id="estimate-description" required maxLength={5000} rows={5} placeholder="Tell us what work you have in mind, any requirements and your timeline." value={f.formData.description} aria-invalid={Boolean(f.fieldErrors.description)} aria-describedby={f.fieldErrors.description?"estimate-error-description":undefined} onChange={e=>f.setFormData({...f.formData,description:e.target.value})}/>{f.fieldErrors.description&&<span id="estimate-error-description" className={styles.estimateFieldError}>{f.fieldErrors.description}</span>}</label>
   <details className={styles.estimateExtras}><summary>Add photos or measurements <span>(optional)</span></summary><label className={styles.estimateField} htmlFor="estimate-photos">Project photos<input id="estimate-photos" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={f.handleFileUpload}/><small>Up to 5 JPEG, PNG or WebP photos, 10 MB each. These go privately to the contractor, not onto their website.</small></label><ul>{f.uploadedFiles.map((file,index)=><li key={`${file.name}-${index}`}>{file.name} <button type="button" aria-label={`Remove photo ${file.name}`} onClick={()=>f.removeFile(index)}>Remove</button></li>)}</ul><MeasurementsInput minimal value={f.measurements} onChange={f.setMeasurements}/></details>
   <div className={styles.estimateTrap} aria-hidden="true"><label htmlFor="estimate-company-website">Company website</label><input id="estimate-company-website" tabIndex={-1} autoComplete="off" value={f.honeypot} onChange={e=>f.setHoneypot(e.target.value)}/></div>
  </fieldset>
  {!preview&&ready===true&&siteKey&&<EstimateChallenge key={f.challengeGeneration} siteKey={siteKey} onToken={f.setChallengeToken}/>}
  <div role="status" aria-live="polite">{f.isSubmitting?"Sending your request...":""}</div>
  <button className={styles.primary} type="submit" disabled={f.isSubmitting||ready!==true||preview||!f.challengeToken}>{f.isSubmitting?"Sending...":f.locked?"Retry the same request":"Send estimate request"}</button>
  <p className={styles.estimateNote}>This requests an estimate. It does not book work or take payment.</p>
 </form>
}
